export const CARD_TYPE_CORRUPTION = 1
export const CARD_TYPE_PROPAGANDA = 2
export const CARD_TYPE_HACKING = 3
export const CARD_TYPE_HARDWARE = 4
export const CARD_TYPE_VIRUS = 5

export const SPECIAL_EFFECT_NONE = 0
export const SPECIAL_EFFECT_PROPAGANDA_PER_PROPAGANDA_CARD = 3
export const SPECIAL_EFFECT_HACKING_PER_VIRUS_CARD = 5
export const SPECIAL_EFFECT_CORRUPTION_PER_CORRUPTION_CARD = 7
